In [2]:
import pandas as pd
import os

In [6]:
continents = pd.read_csv(
    os.path.join("data", "continents.csv"),
)
continents["continent"] = continents["continent"].str.replace("_", " ")
continents["continent"] = continents["continent"].replace({"Oceania": "Australia"})

display(continents)

                               article      continent
0     %C3%81ed%C3%A1n_mac_Gabr%C3%A1in         Europe
1                           %C3%85land         Europe
2                   %C3%89douard_Manet         Europe
3                            %C3%89ire         Europe
4           %C3%93engus_I_of_the_Picts         Europe
...                                ...            ...
4599                           Zionism           Asia
4600                         Zirconium  International
4601                         Zoroaster           Asia
4602                      Zuid-Gelders         Europe
4603                              Zulu         Africa

[4604 rows x 2 columns]

In [4]:
categories = pd.read_csv(
    os.path.join("data", "wikispeedia_paths-and-graph", "categories.tsv"),
    delimiter="\t",
    header=None,
    names=["article", "category"],
    skip_blank_lines=True,
    comment="#",
    encoding="UTF-8"
)

categories.head()

,article,category
0,%C3%81ed%C3%A1n_mac_Gabr%C3%A1in,subject.History.British_History.British_Histor...
1,%C3%81ed%C3%A1n_mac_Gabr%C3%A1in,subject.People.Historical_figures
2,%C3%85land,subject.Countries
3,%C3%85land,subject.Geography.European_Geography.European_...
4,%C3%89douard_Manet,subject.People.Artists

## Changing continents based on categories seen

In [67]:
def change_continent(article_name, continent):
    row_index = continents.index[continents.article == article_name].item()
    continents.loc[row_index,'continent'] = continent
    #print(continents[continents.article == article_name])

In [68]:
#Space
change_continent('Apollo_11','North America')
change_continent('Apollo_8','North America')
change_continent('Moon_landing','North America')
change_continent('Phoenix_%28spacecraft%29','North America')
change_continent('Sputnik_1','Europe')
change_continent('Sputnik_2','Europe')
change_continent('Sputnik_program','Europe')
change_continent('Caloris_Basin','International')

In [113]:
#Science
change_continent('Atom','International')

#Animals
change_continent('Box_jellyfish','International')
change_continent('Basking_shark','International')
change_continent('Bass_%28fish%29','International')
change_continent('Brown_trout','International')
change_continent('Cane_Toad', 'International')
change_continent('Goldfish', 'International')
change_continent('Marginated_Tortoise', 'International')
change_continent('Badger', 'International')

#Birds
change_continent('Archaeopteryx','International')
change_continent('Arctic_Tern','International')
change_continent('Barn_Owl','International')
change_continent('Blackbird','International')
change_continent('Coal_Tit', 'International')
change_continent('Common_Cuckoo', 'International')
change_continent('Common_Eider', 'International')
change_continent('Common_Tern', 'International')
change_continent('Fieldfare','International')

In [122]:
#Religion
change_continent('Allegory_in_the_Middle_Ages', 'International')
change_continent('Pentateuch','International')
change_continent('Qur%27an','International')
change_continent('Vinaya','Asia')

In [123]:
#Medicine
change_continent('Achilles_tendon','International')
change_continent('Lyme_disease','International')
change_continent('The_Origin_of_Species','International')

In [131]:
#People
change_continent('David_Heymann','North America')
change_continent('Edmund_Hillary','Australia')
change_continent('Euclid','Europe')
change_continent('Ferdinand_Magellan','Europe')
change_continent('H.D.','North America')
change_continent('Helen','Europe')
change_continent('Rebecca_Helferich_Clarke','Europe')
change_continent('Stephen_Trigg','North America')
change_continent('Vasco_da_Gama','Europe')

In [140]:
#Music
change_continent('AC_DC','Australia')
change_continent('Iron_Maiden','Europe')
change_continent('U2','Europe')
change_continent('Himno_Nacional_Mexicano','South_America')
change_continent('Bassoon','International')

In [170]:
#IT
change_continent('ZX_Spectrum','International')
change_continent('BASIC','International')
change_continent('Forth','International')

#Food
change_continent('Paprika','International')

In [173]:
#Transport
change_continent('Automatic_number_plate_recognition','International')

#Rights
change_continent('Civil_rights','International')

In [157]:
#Plants => All International but Wasabi
for article in categories[categories.category == "subject.Science.Biology.Plants"]['article'].values:
    if article != 'Wasabi':
        change_continent(article,'International')

In [164]:
#Dinosaurs => All international
for article in categories[categories.category == "subject.Science.Biology.Dinosaurs"]['article'].values:
    change_continent(article,'International')

for article in categories[categories.category == "subject.Everyday_life.Recreation"]['article'].values:
    change_continent(article,'International')

In [165]:
articles = pd.merge(categories, continents, on="article", how="inner")
articles = articles.fillna("")
articles.head()

,article,category,continent
0,%C3%81ed%C3%A1n_mac_Gabr%C3%A1in,subject.History.British_History.British_Histor...,Europe
1,%C3%81ed%C3%A1n_mac_Gabr%C3%A1in,subject.People.Historical_figures,Europe
2,%C3%85land,subject.Countries,Europe
3,%C3%85land,subject.Geography.European_Geography.European_...,Europe
4,%C3%89douard_Manet,subject.People.Artists,Europe

In [166]:
category_counts = categories.category.value_counts().reset_index().rename(columns={"count": "total"})

In [5]:
pd.reset_option('display.max_rows')

In [168]:
continents_categories = articles.groupby("continent").value_counts(["category"]).reset_index()
continents_categories = pd.merge(continents_categories, category_counts, on="category", how="left")

continents_categories["percentage"] = continents_categories["count"] / continents_categories["total"]

#display(continents_categories.sort_values("percentage", ascending=False))

- The 1 in Astronomy is Edmund Halley - Europe
- The 1 in Physics is Schrodinger's-Equation - Europe
- The 1 in materials science is Ivory - Africa (Makes sense)
- The 1 in Chemical Elements is Californium - NA

In [169]:
categories_continents = articles.groupby("category").value_counts(["continent"]).groupby(level=0).head(3).reset_index()
categories_continents = pd.merge(categories_continents, category_counts, on="category", how="left")

categories_continents["percentage"] = categories_continents["count"] / categories_continents["total"]

categories_continents.sort_values(["category", "percentage"], ascending=False)

,category,continent,count,total,percentage
313,subject.Science.Physics.The_Planets,International,13,13,1.000000
310,subject.Science.Physics.Space_transport,International,20,33,0.606061
311,subject.Science.Physics.Space_transport,Europe,6,33,0.181818
312,subject.Science.Physics.Space_transport,North America,5,33,0.151515
308,subject.Science.Physics.Space_Astronomy,International,104,105,0.990476
309,subject.Science.Physics.Space_Astronomy,Europe,1,105,0.009524
306,subject.Science.Physics.General_Physics,International,54,55,0.981818
307,subject.Science.Physics.General_Physics,Europe,1,55,0.018182
305,subject.Science.Physics.Electricity_and_Electr...,International,20,20,1.000000
303,subject.Science.Chemistry.Materials_science,International,9,10,0.900000
304,subject.Science.Chemistry.Materials_science,Africa,1,10,0.100000
302,subject.Science.Chemistry.General_Chemistry,International,21,21,1.000000
300,subject.Science.Chemistry.Chemical_elements,International,118,119,0.991597
301,subject.Science.Chemistry.Chemical_elements,North America,1,119,0.008403
299,subject.Science.Chemistry.Chemical_compounds,International,42,42,1.000000
297,subject.Science.Biology.Plants,International,107,108,0.990741
298,subject.Science.Biology.Plants,Asia,1,108,0.009259
296,subject.Science.Biology.Organisms,International,19,19,1.000000
293,subject.Science.Biology.Mammals,Africa,45,114,0.394737
294,subject.Science.Biology.Mammals,International,41,114,0.359649
295,subject.Science.Biology.Mammals,Asia,9,114,0.078947
290,subject.Science.Biology.Insects_Reptiles_and_Fish,International,57,72,0.791667
291,subject.Science.Biology.Insects_Reptiles_and_Fish,Africa,4,72,0.055556
292,subject.Science.Biology.Insects_Reptiles_and_Fish,Australia,3,72,0.041667
287,subject.Science.Biology.Health_and_medicine,International,106,109,0.972477
288,subject.Science.Biology.Health_and_medicine,North America,2,109,0.018349
289,subject.Science.Biology.Health_and_medicine,Australia,1,109,0.009174
284,subject.Science.Biology.General_Biology,International,49,51,0.960784
285,subject.Science.Biology.General_Biology,Australia,1,51,0.019608
286,subject.Science.Biology.General_Biology,North America,1,51,0.019608
282,subject.Science.Biology.Evolution_and_reproduc...,International,9,11,0.818182
283,subject.Science.Biology.Evolution_and_reproduc...,North America,2,11,0.181818
281,subject.Science.Biology.Dinosaurs,International,59,59,1.000000
278,subject.Science.Biology.Birds,International,96,161,0.596273
279,subject.Science.Biology.Birds,Europe,24,161,0.149068
280,subject.Science.Biology.Birds,Australia,12,161,0.074534
275,subject.Religion.Religious_texts,Asia,7,18,0.388889
276,subject.Religion.Religious_texts,International,6,18,0.333333
277,subject.Religion.Religious_texts,Europe,5,18,0.277778
272,subject.Religion.Religious_movements_tradition...,Europe,12,35,0.342857
273,subject.Religion.Religious_movements_tradition...,Asia,10,35,0.285714
274,subject.Religion.Religious_movements_tradition...,International,9,35,0.257143
269,subject.Religion.Religious_disputes,Europe,9,19,0.473684
270,subject.Religion.Religious_disputes,International,9,19,0.473684
271,subject.Religion.Religious_disputes,Asia,1,19,0.052632
266,subject.Religion.Philosophy,International,19,24,0.791667
267,subject.Religion.Philosophy,Asia,3,24,0.125000
268,subject.Religion.Philosophy,Europe,2,24,0.083333
263,subject.Religion.Myths,Europe,9,17,0.529412
264,subject.Religion.Myths,International,7,17,0.411765
265,subject.Religion.Myths,North America,1,17,0.058824
260,subject.Religion.Divinities,Asia,8,21,0.380952
261,subject.Religion.Divinities,International,7,21,0.333333
262,subject.Religion.Divinities,Europe,4,21,0.190476
257,subject.People.Writers_and_critics,Europe,48,71,0.676056
258,subject.People.Writers_and_critics,North America,15,71,0.211268
259,subject.People.Writers_and_critics,Asia,5,71,0.070423
256,subject.People.USA_Presidents,North America,37,37,1.000000
253,subject.People.Sports_and_games_people,Europe,20,45,0.444444
254,subject.People.Sports_and_games_people,North America,17,45,0.377778
255,subject.People.Sports_and_games_people,Australia,4,45,0.088889
250,subject.People.Religious_figures_and_leaders,Europe,25,39,0.641026
251,subject.People.Religious_figures_and_leaders,Asia,8,39,0.205128
252,subject.People.Religious_figures_and_leaders,Africa,4,39,0.102564
247,subject.People.Producers_directors_and_media_f...,North America,4,8,0.500000
248,subject.People.Producers_directors_and_media_f...,Europe,3,8,0.375000
249,subject.People.Producers_directors_and_media_f...,Asia,1,8,0.125000
244,subject.People.Political_People,Europe,31,67,0.462687
245,subject.People.Political_People,North America,19,67,0.283582
246,subject.People.Political_People,Asia,12,67,0.179104
241,subject.People.Philosophers,Europe,18,23,0.782609
242,subject.People.Philosophers,North America,3,23,0.130435
243,subject.People.Philosophers,Asia,2,23,0.086957
238,subject.People.Performers_and_composers,Europe,27,43,0.627907
239,subject.People.Performers_and_composers,North America,15,43,0.348837
240,subject.People.Performers_and_composers,Australia,1,43,0.023256
237,subject.People.Monarchs_of_Great_Britain,Europe,43,43,1.000000
234,subject.People.Military_People,Europe,14,22,0.636364
235,subject.People.Military_People,North America,7,22,0.318182
236,subject.People.Military_People,Asia,1,22,0.045455
232,subject.People.Mathematicians,Europe,14,15,0.933333
233,subject.People.Mathematicians,North America,1,15,0.066667
230,subject.People.Human_Scientists,Europe,18,23,0.782609
231,subject.People.Human_Scientists,North America,5,23,0.217391
227,subject.People.Historical_figures,Europe,61,108,0.564815
228,subject.People.Historical_figures,North America,18,108,0.166667
229,subject.People.Historical_figures,Asia,16,108,0.148148
224,subject.People.Geographers_and_explorers,Europe,14,21,0.666667
225,subject.People.Geographers_and_explorers,North America,3,21,0.142857
226,subject.People.Geographers_and_explorers,Australia,2,21,0.095238
221,subject.People.Engineers_and_inventors,Europe,15,25,0.600000
222,subject.People.Engineers_and_inventors,North America,8,25,0.320000
223,subject.People.Engineers_and_inventors,Asia,1,25,0.040000
219,subject.People.Computing_People,North America,6,9,0.666667
220,subject.People.Computing_People,Europe,3,9,0.333333
217,subject.People.Chemists,Europe,7,8,0.875000
218,subject.People.Chemists,North America,1,8,0.125000
214,subject.People.Astronomers_and_physicists,Europe,13,21,0.619048
215,subject.People.Astronomers_and_physicists,North America,6,21,0.285714
216,subject.People.Astronomers_and_physicists,Africa,1,21,0.047619
211,subject.People.Artists,Europe,33,36,0.916667
212,subject.People.Artists,North America,2,36,0.055556
213,subject.People.Artists,Asia,1,36,0.027778
208,subject.People.Actors_models_and_celebrities,North America,14,25,0.560000
209,subject.People.Actors_models_and_celebrities,Europe,8,25,0.320000
210,subject.People.Actors_models_and_celebrities,Asia,2,25,0.080000
205,subject.Music.Performers_and_composers,Europe,10,16,0.625000
206,subject.Music.Performers_and_composers,North America,4,16,0.250000
207,subject.Music.Performers_and_composers,Africa,1,16,0.062500
202,subject.Music.Musical_genres_styles_eras_and_e...,Europe,12,46,0.260870
203,subject.Music.Musical_genres_styles_eras_and_e...,North America,12,46,0.260870
204,subject.Music.Musical_genres_styles_eras_and_e...,International,10,46,0.217391
199,subject.Music.Musical_Recordings_and_compositions,Europe,11,18,0.611111
200,subject.Music.Musical_Recordings_and_compositions,International,4,18,0.222222
201,subject.Music.Musical_Recordings_and_compositions,North America,2,18,0.111111
197,subject.Music.Musical_Instruments,International,15,17,0.882353
198,subject.Music.Musical_Instruments,Asia,2,17,0.117647
195,subject.Mathematics,International,44,45,0.977778
196,subject.Mathematics,Asia,1,45,0.022222
192,subject.Language_and_literature.Theatre,Europe,24,32,0.750000
193,subject.Language_and_literature.Theatre,International,7,32,0.218750
194,subject.Language_and_literature.Theatre,North America,1,32,0.031250
189,subject.Language_and_literature.Poetry_and_Opera,Europe,18,30,0.600000
190,subject.Language_and_literature.Poetry_and_Opera,International,7,30,0.233333
191,subject.Language_and_literature.Poetry_and_Opera,Asia,3,30,0.100000
186,subject.Language_and_literature.Novels,Europe,23,39,0.589744
187,subject.Language_and_literature.Novels,International,9,39,0.230769
188,subject.Language_and_literature.Novels,North America,7,39,0.179487
183,subject.Language_and_literature.Literature_types,International,8,17,0.470588
184,subject.Language_and_literature.Literature_types,Europe,6,17,0.352941
185,subject.Language_and_literature.Literature_types,Asia,2,17,0.117647
180,subject.Language_and_literature.Linguistics,International,8,15,0.533333
181,subject.Language_and_literature.Linguistics,Europe,4,15,0.266667
182,subject.Language_and_literature.Linguistics,Asia,2,15,0.133333
177,subject.Language_and_literature.Languages,Europe,17,47,0.361702
178,subject.Language_and_literature.Languages,International,11,47,0.234043
179,subject.Language_and_literature.Languages,Africa,9,47,0.191489
174,subject.Language_and_literature.General_Litera...,Europe,9,16,0.562500
175,subject.Language_and_literature.General_Litera...,International,6,16,0.375000
176,subject.Language_and_literature.General_Litera...,Asia,1,16,0.062500
173,subject.IT.Websites_and_the_Internet,International,21,21,1.000000
171,subject.IT.Software,International,20,23,0.869565
172,subject.IT.Software,North America,3,23,0.130435
169,subject.IT.Cryptography,International,5,6,0.833333
170,subject.IT.Cryptography,Europe,1,6,0.166667
166,subject.IT.Computing_hardware_and_infrastructure,International,18,20,0.900000
167,subject.IT.Computing_hardware_and_infrastructure,North America,1,20,0.050000
168,subject.IT.Computing_hardware_and_infrastructure,Europe,1,20,0.050000
165,subject.IT.Computer_Programming,International,15,15,1.000000
162,subject.History.World_War_II,Europe,20,31,0.645161
163,subject.History.World_War_II,Australia,5,31,0.161290
164,subject.History.World_War_II,Asia,4,31,0.129032
159,subject.History.Recent_History,Europe,16,48,0.333333
160,subject.History.Recent_History,North America,11,48,0.229167
161,subject.History.Recent_History,International,8,48,0.166667
156,subject.History.Pre_1900_Military,Europe,20,27,0.740741
157,subject.History.Pre_1900_Military,North America,5,27,0.185185
158,subject.History.Pre_1900_Military,Africa,1,27,0.037037
155,subject.History.North_American_History,North America,22,22,1.000000
152,subject.History.Military_History_and_War,Europe,32,71,0.450704
153,subject.History.Military_History_and_War,International,18,71,0.253521
154,subject.History.Military_History_and_War,North America,9,71,0.126761
150,subject.History.Historians_chroniclers_and_his...,Europe,9,10,0.900000
151,subject.History.Historians_chroniclers_and_his...,Asia,1,10,0.100000
147,subject.History.General_history,Europe,33,80,0.412500
148,subject.History.General_history,International,28,80,0.350000
149,subject.History.General_history,Asia,8,80,0.100000
144,subject.History.British_History.British_Histor...,Europe,14,18,0.777778
145,subject.History.British_History.British_Histor...,International,3,18,0.166667
146,subject.History.British_History.British_Histor...,Asia,1,18,0.055556
142,subject.History.British_History.British_Histor...,Europe,22,24,0.916667
143,subject.History.British_History.British_Histor...,Africa,2,24,0.083333
141,subject.History.British_History.British_Histor...,Europe,73,73,1.000000
139,subject.History.British_History.British_Histor...,Europe,28,29,0.965517
140,subject.History.British_History.British_Histor...,International,1,29,0.034483
137,subject.History.British_History,Europe,9,14,0.642857
138,subject.History.British_History,International,5,14,0.357143
134,subject.History.Archaeology,Africa,6,11,0.545455
135,subject.History.Archaeology,International,2,11,0.181818
136,subject.History.Archaeology,Europe,2,11,0.181818
131,subject.History.Ancient_History_Classical_Hist...,Europe,35,87,0.402299
132,subject.History.Ancient_History_Classical_Hist...,Asia,25,87,0.287356
133,subject.History.Ancient_History_Classical_Hist...,International,11,87,0.126437
128,subject.Geography.Storms,North America,26,33,0.787879
129,subject.Geography.Storms,International,5,33,0.151515
130,subject.Geography.Storms,Asia,2,33,0.060606
125,subject.Geography.Peoples,Europe,8,22,0.363636
126,subject.Geography.Peoples,Asia,5,22,0.227273
127,subject.Geography.Peoples,North America,4,22,0.181818
123,subject.Geography.North_American_Geography,North America,102,103,0.990291
124,subject.Geography.North_American_Geography,Africa,1,103,0.009709
120,subject.Geography.Natural_Disasters,North America,21,39,0.538462
121,subject.Geography.Natural_Disasters,International,8,39,0.205128
122,subject.Geography.Natural_Disasters,Asia,5,39,0.128205
119,subject.Geography.Mineralogy,International,17,17,1.000000
116,subject.Geography.Geology_and_geophysics,International,66,76,0.868421
117,subject.Geography.Geology_and_geophysics,North America,4,76,0.052632
118,subject.Geography.Geology_and_geophysics,Europe,3,76,0.039474
115,subject.Geography.Geography_of_the_Middle_East...,Asia,18,18,1.000000
113,subject.Geography.Geography_of_the_Middle_East,Asia,17,18,0.944444
114,subject.Geography.Geography_of_the_Middle_East,Africa,1,18,0.055556
112,subject.Geography.Geography_of_Oceania_Austral...,Australia,58,58,1.000000
111,subject.Geography.Geography_of_Great_Britain,Europe,124,124,1.000000
109,subject.Geography.Geography_of_Asia.Asian_Coun...,Asia,36,37,0.972973
110,subject.Geography.Geography_of_Asia.Asian_Coun...,Australia,1,37,0.027027
106,subject.Geography.Geography_of_Asia,Asia,65,69,0.942029
107,subject.Geography.Geography_of_Asia,Europe,1,69,0.014493
108,subject.Geography.Geography_of_Asia,International,1,69,0.014493
103,subject.Geography.General_Geography,International,23,65,0.353846
104,subject.Geography.General_Geography,Asia,15,65,0.230769
105,subject.Geography.General_Geography,Europe,11,65,0.169231
101,subject.Geography.European_Geography.European_...,Europe,55,56,0.982143
102,subject.Geography.European_Geography.European_...,Asia,1,56,0.017857
100,subject.Geography.European_Geography,Europe,83,83,1.000000
99,subject.Geography.Climate_and_the_Weather,International,38,38,1.000000
98,subject.Geography.Central_and_South_American_G...,South America,48,48,1.000000
97,subject.Geography.Central_and_South_American_G...,South America,35,35,1.000000
94,subject.Geography.Antarctica,Antarctica,5,8,0.625000
95,subject.Geography.Antarctica,International,2,8,0.250000
96,subject.Geography.Antarctica,Australia,1,8,0.125000
93,subject.Geography.African_Geography.African_Co...,Africa,57,57,1.000000
91,subject.Geography.African_Geography,Africa,76,80,0.950000
92,subject.Geography.African_Geography,Asia,4,80,0.050000
88,subject.Everyday_life.Television,Europe,20,41,0.487805
89,subject.Everyday_life.Television,North America,10,41,0.243902
90,subject.Everyday_life.Television,International,10,41,0.243902
85,subject.Everyday_life.Sports_teams,Europe,8,16,0.500000
86,subject.Everyday_life.Sports_teams,North America,4,16,0.250000
87,subject.Everyday_life.Sports_teams,Asia,2,16,0.125000
82,subject.Everyday_life.Sports_events,International,12,22,0.545455
83,subject.Everyday_life.Sports_events,Europe,5,22,0.227273
84,subject.Everyday_life.Sports_events,North America,3,22,0.136364
79,subject.Everyday_life.Sports,International,23,32,0.718750
80,subject.Everyday_life.Sports,North America,4,32,0.125000
81,subject.Everyday_life.Sports,Asia,2,32,0.062500
78,subject.Everyday_life.Recreation,International,21,21,1.000000
75,subject.Everyday_life.Games,International,17,21,0.809524
76,subject.Everyday_life.Games,Asia,3,21,0.142857
77,subject.Everyday_life.Games,Africa,1,21,0.047619
72,subject.Everyday_life.Food_and_agriculture,International,87,97,0.896907
73,subject.Everyday_life.Food_and_agriculture,Asia,4,97,0.041237
74,subject.Everyday_life.Food_and_agriculture,Europe,3,97,0.030928
69,subject.Everyday_life.Films,North America,15,36,0.416667
70,subject.Everyday_life.Films,International,15,36,0.416667
71,subject.Everyday_life.Films,Europe,5,36,0.138889
67,subject.Everyday_life.Everyday_life,International,26,27,0.962963
68,subject.Everyday_life.Everyday_life,Asia,1,27,0.037037
64,subject.Everyday_life.Drink,International,10,15,0.666667
65,subject.Everyday_life.Drink,Europe,4,15,0.266667
66,subject.Everyday_life.Drink,Asia,1,15,0.066667
61,subject.Everyday_life.Computer_and_Video_games,International,19,26,0.730769
62,subject.Everyday_life.Computer_and_Video_games,Asia,4,26,0.153846
63,subject.Everyday_life.Computer_and_Video_games,North America,2,26,0.076923
58,subject.Everyday_life.Cartoons,North America,11,20,0.550000
59,subject.Everyday_life.Cartoons,International,5,20,0.250000
60,subject.Everyday_life.Cartoons,Europe,4,20,0.200000
55,subject.Design_and_Technology.Road_transport,Europe,11,19,0.578947
56,subject.Design_and_Technology.Road_transport,North America,5,19,0.263158
57,subject.Design_and_Technology.Road_transport,International,3,19,0.157895
52,subject.Design_and_Technology.Railway_transport,North America,42,84,0.500000
53,subject.Design_and_Technology.Railway_transport,International,22,84,0.261905
54,subject.Design_and_Technology.Railway_transport,Europe,14,84,0.166667
49,subject.Design_and_Technology.Engineering,International,60,74,0.810811
50,subject.Design_and_Technology.Engineering,Europe,10,74,0.135135
51,subject.Design_and_Technology.Engineering,Asia,2,74,0.027027
46,subject.Design_and_Technology.Architecture,Europe,32,53,0.603774
47,subject.Design_and_Technology.Architecture,North America,7,53,0.132075
48,subject.Design_and_Technology.Architecture,International,5,53,0.094340
43,subject.Design_and_Technology.Air_and_Sea_tran...,International,14,24,0.583333
44,subject.Design_and_Technology.Air_and_Sea_tran...,Europe,5,24,0.208333
45,subject.Design_and_Technology.Air_and_Sea_tran...,North America,3,24,0.125000
40,subject.Countries,Europe,55,229,0.240175
41,subject.Countries,Asia,55,229,0.240175
42,subject.Countries,Africa,52,229,0.227074
37,subject.Citizenship.Politics_and_government,International,51,97,0.525773
38,subject.Citizenship.Politics_and_government,Europe,22,97,0.226804
39,subject.Citizenship.Politics_and_government,North America,12,97,0.123711
34,subject.Citizenship.Media,International,8,11,0.727273
35,subject.Citizenship.Media,Asia,1,11,0.090909
36,subject.Citizenship.Media,Europe,1,11,0.090909
31,subject.Citizenship.Law,International,10,19,0.526316
32,subject.Citizenship.Law,North America,7,19,0.368421
33,subject.Citizenship.Law,Europe,2,19,0.105263
29,subject.Citizenship.Environment,International,25,26,0.961538
30,subject.Citizenship.Environment,South America,1,26,0.038462
26,subject.Citizenship.Education,International,8,17,0.470588
27,subject.Citizenship.Education,Europe,5,17,0.294118
28,subject.Citizenship.Education,North America,2,17,0.117647
24,subject.Citizenship.Culture_and_Diversity,International,15,16,0.937500
25,subject.Citizenship.Culture_and_Diversity,Europe,1,16,0.062500
21,subject.Citizenship.Conflict_and_Peace,International,5,10,0.500000
22,subject.Citizenship.Conflict_and_Peace,Africa,3,10,0.300000
23,subject.Citizenship.Conflict_and_Peace,Asia,2,10,0.200000
18,subject.Citizenship.Community_organisations,International,5,11,0.454545
19,subject.Citizenship.Community_organisations,North America,4,11,0.363636
20,subject.Citizenship.Community_organisations,Europe,2,11,0.181818
16,subject.Citizenship.Animal_and_Human_Rights,International,16,17,0.941176
17,subject.Citizenship.Animal_and_Human_Rights,North America,1,17,0.058824
13,subject.Business_Studies.Economics,International,16,28,0.571429
14,subject.Business_Studies.Economics,Europe,7,28,0.250000
15,subject.Business_Studies.Economics,Asia,2,28,0.071429

In [24]:
# I am here modifying elements that I find
def change_continent(article_name, continent):
    row_index = continents.index[continents.article == article_name].item()
    continents.loc[row_index,'continent'] = continent
    print(continents[continents.article == article_name])

       article      continent
302  Apollo_11  North America
      article      continent
303  Apollo_8  North America
           article      continent
2833  Moon_landing  North America